version: "3"
services:
  nuxtjs:
    build: ./docker/nuxtjs/
    container_name: node-api
    tty: true
    stdin_open: true
    cap_add:
      - SYS_ADMIN
    shm_size: 256
    command: npm run dev
    volumes:
      - ./app:/app
    ports:
      - 5000:3000
